### ISSUE TITLE
hidesBottomBarWhenPushed

### ISSUE THREAD

**Issue by hutchy** [BasheerSience/BROptionsButton#5]
Due to this being added as a subview of the tabBar.superview I wonder if anyone has found a reliable way to get this working.

I have experimented by adding it directly to the .tabBar however this creates issues with the UI and auto layout (to ensure the button fits correctly on iPhone 6 and above).

Thanks, Ben

**Comment by BasheerSience** [comment]
Hi, Ben. 
Thanks for your comment, I've just pushed the fix for this issue, please pull the latest changes,
Thanks,
Basheer

**Comment by hutchy** [comment]
Thanks Basheer, impressive response! Do you have any thoughts how we get this working when hidesBottomBarWhenPushed = YES is invoked?

**Comment by BasheerSience** [comment]
I think we have a solution for that, by adding the button to the tabbar instead of superview, I will check that tomorrow and let you know. 
Thanks for your feedback

**Comment by BasheerSience** [comment]
This problem was fixed, please close this issue
