### ISSUE TITLE
still doesn't work well when hidesBottomBarWhenPushed

### ISSUE THREAD

**Issue by Wstunes** [BasheerSience/BROptionsButton#6]
I'm using storyboard to push to a new viewController.
The tabBar hides but the BROptionsButton in the middle of the tabBar won't hide
when popped to the previous viewController, the tabBar appears but the BROptionsButton won't appear

**Comment by BasheerSience** [comment]
hi,
I will check that today ASAP, and give you a feedback

**Comment by BasheerSience** [comment]
@Wstunes, please check the last update, now your issue should be fixed. 
Please close the issue if the control works fine
